# Generated by Django 2.2.7 on 2019-12-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_teacher_of',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
