# Generated by Django 2.2.7 on 2019-12-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191207_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('marks_in_theory', models.CharField(max_length=50)),
                ('marks_in_practical', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=50)),
                ('period_1', models.CharField(max_length=50)),
                ('period_2', models.CharField(max_length=50)),
                ('period_3', models.CharField(max_length=50)),
                ('period_4', models.CharField(max_length=50)),
                ('period_5', models.CharField(max_length=50)),
                ('period_6', models.CharField(max_length=50)),
                ('period_7', models.CharField(max_length=50)),
                ('period_8', models.CharField(max_length=50)),
                ('period_9', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='active',
        ),
        migrations.DeleteModel(
            name='teacher_timetable',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='addhar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='e_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.teacher'),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='adm_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.teacher'),
        ),
    ]
