# Generated by Django 2.2.7 on 2019-12-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191209_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='addhar_no',
            field=models.BigIntegerField(),
        ),
    ]
