# Generated by Django 2.2.7 on 2019-12-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191209_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_marks',
            name='adm_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.student'),
        ),
    ]
